### ISSUE TITLE
can't run (QML exception)

### ISSUE THREAD

**Issue by r3d9u11** [AlfredoCubitos/MNote2#1]
Hello. I've just tried to compile and run it on KDE Neon with Qt 5.14.1, but I've got exception:

```
22:48:17: Debugging starts
QML debugging is enabled. Only use this in a safe environment.
QML Debugger: Waiting for connection on port 41843...
SSL supported "OpenSSL 1.1.1  11 Sep 2018"
QQmlComponent: Component is not ready
QObject::connect: Cannot connect (nullptr)::searchSignal(QString, QString) to MNotesHandler::searchSignal(QString, QString)
QObject::connect: Cannot connect (nullptr)::findNext() to MNotesHandler::findNext()
```
Do you have any ideas?
Thanks!

**Comment by AlfredoCubitos** [comment]
Hm, strange.
When I compile it with the Qt Environment 5.14.2 I got the same error.
Also I get some `deprecated warnings`
But when I compile it in my KDE environment with Qt 5.14.1 on openSuse Tumbleweed it runs

**Comment by AlfredoCubitos** [comment]
ok, I found the error.
You have to install kde prison.
I made an update, which shows the error message.
If you have installed the opensource Qt environment maybe that doesn't work either, because `qmlplugindump` does not recognize the plugin
So better use your official qt5 developer environment from your distro

**Comment by r3d9u11** [comment]
@AlfredoCubitos Thanks for answer and useful hints!

I installed prison on my KDE Neon: `sudo apt install libprison-dev`
and found lib's path:
```
$ whereis libprison.so
libprison: /usr/lib/x86_64-linux-gnu/libprison.so
```
Then I added those line to end of the .pro file:
```
HEADERS += /usr/include/prison
LIBS += -L/usr/lib/x86_64-linux-gnu -lprison
```
And now it works!
