### ISSUE TITLE
warning due to add new note

### ISSUE THREAD

**Issue by r3d9u11** [AlfredoCubitos/MNote2#2]
Hello. There is warning due to add new note, because `selectionStart` in
https://github.com/AlfredoCubitos/MNote2/blob/master/main.qml#L201
is readonly:
https://doc.qt.io/qt-5/qml-qtquick-textedit.html#selectionStart-prop
I think, `cursorPosition` should be used instead of it:
https://doc.qt.io/qt-5/qml-qtquick-textedit.html#cursorPosition-prop
(maybe different version of Qt)

**Comment by AlfredoCubitos** [comment]
The selectionStart is only used with the search function.
Please describe what you have done to produce this error

**Comment by r3d9u11** [comment]
@AlfredoCubitos Sorry, there is a bit mistake, I've that warning when I'm trying to add new note:
```
qrc:/main.qml:201: TypeError: Cannot assign to read-only property "selectionStart" qrc:/main.qml: 201
```

**Comment by AlfredoCubitos** [comment]
aah, ok
Thank you for your advise.
